# DfGrid_Common.o			\
# Fl_KeywordX.o				\
#  TlListMatrix.o				\
# DfEnergyWeightedDensityMatrix.o	\
#  RunoutputX_parallel.o			\
#  TlLog_Parallel.o			
#  TlSparseHashMatrix.o			\
#  TlSparseHashSymmetricMatrix.o		\


OBJS = \
 CnError.o			\
 DfCalcGrid.o			\
 DfCalcGridX.o			\
 DfCleanup.o			\
 DfConvcheck.o			\
 DfConverge.o			\
 DfConverge2.o			\
 DfConverge_Anderson.o		\
 DfConverge_Damping.o		\
 DfCqclomatrix.o		\
 DfDensityFitting.o		\
 DfDiagonal.o			\
 DfDiffDensityMatrix.o		\
 DfDmatrix.o			\
 DfEri.o			\
 DfEri2.o			\
 DfEriEngine.o			\
 DfEriX.o			\
 DfFockMatrix.o			\
 DfForce.o			\
 DfFunctional.o			\
 DfFunctional_B3LYP.o		\
 DfFunctional_B88LYP.o		\
 DfFunctional_Becke88.o		\
 DfFunctional_Becke88_ExceptLDA.o	\
 DfFunctional_LYP.o			\
 DfFunctional_PW91X.o			\
 DfFunctional_SHF.o			\
 DfFunctional_SVWN.o			\
 DfFunctional_Slater.o			\
 DfFunctional_VWN.o			\
 DfFunctional_VWN3.o			\
 DfGenerateGrid.o			\
 DfHpq.o				\
 DfHpqEngine.o				\
 DfHpq_driver.o				\
 DfHpqX.o				\
 DfIGuess2.o				\
 DfInitialGuess.o			\
 DfInitialGuessHarris.o			\
 DfInitialGuessHuckel.o			\
 DfInitialguess.o			\
 DfInputdata.o				\
 DfIntegrals.o				\
 DfInvMatrix.o				\
 DfJMatrix.o				\
 DfLevelshift.o				\
 DfObject.o				\
 DfOverlap.o				\
 DfOverlapEngine.o			\
 DfOverlapX.o				\
 DfPopulation.o				\
 DfPreScf.o				\
 DfQclo.o				\
 DfRLMO.o				\
 DfScf.o				\
 DfSummary.o				\
 DfTaskCtrl.o				\
 DfTEI.o				\
 DfThreeindexintegrals.o		\
 DfTotalEnergy.o			\
 DfTransFmatrix.o			\
 DfTransatob.o				\
 DfTwoElectronIntegral.o		\
 DfXCFunctional.o			\
 DfXMatrix.o				\
 DfXcenefitting.o			\
 DfXcpotfitting.o			\
 DfXmatrixMyu.o				\
 DfXmatrixNyu.o				\
 DfXmatrixRou.o				\
 FileX.o				\
 Fl_Database.o				\
 Fl_Db_Basis.o				\
 Fl_Fragment.o				\
 Fl_Geometry.o				\
 Fl_GlobalinputX.o			\
 Fl_Gto.o				\
 Fl_GuessDB.o				\
 Fl_Int_Gds.o				\
 Fl_Int_Pqa.o				\
 Fl_Int_Pqg.o				\
 Fl_Integrals.o				\
 Fl_Out.o				\
 Fl_Tbl_AtomFragment.o			\
 Fl_Tbl_Density.o			\
 Fl_Tbl_Fragment.o			\
 Fl_Tbl_Orbital.o			\
 Fl_Tbl_Xcpot.o				\
 Fl_Tbl_Xcpot2.o			\
 Fl_UserinputX.o			\
 Fl_Vct_OtableX.o			\
 Fl_Vct_Table.o				\
 GridDataManager.o			\
 PdfKeyword.o				\
 PdfUserInput.o				\
 PdfUtils.o				\
 ProteinDF.o				\
 TlAngularMomentumVectorSet.o		\
 TlAtom.o				\
 TlCombineDensityMatrix.o		\
 TlCommunicate.o			\
 TlFile.o				\
 TlFileMatrix.o				\
 TlFileSymmetricMatrix.o		\
 TlFmt.o				\
 TlFname.o				\
 TlGetopt.o				\
 TlLogX.o				\
 TlMath.o				\
 TlMatrix.o				\
 TlMatrixCache.o			\
 TlMatrixObject.o			\
 TlMemManager.o				\
 TlMsgPack.o				\
 TlOrbitalInfo.o			\
 TlOrbitalInfoObject.o			\
 TlOrbitalInfo_Density.o		\
 TlOrbitalInfo_XC.o			\
 TlParameter.o				\
 TlPartialMatrix.o			\
 TlPartialSymmetricMatrix.o		\
 TlPosition.o				\
 TlPrdctbl.o				\
 TlPseudoYaml.o				\
 TlResidue.o				\
 TlSerializeData.o			\
 TlSparseMatrix.o			\
 TlSparseSymmetricMatrix.o		\
 TlSparseVectorMatrix.o			\
 TlStringTokenizer.o			\
 TlSymmetricMatrix.o			\
 TlSystem.o				\
 TlTime.o				\
 TlUtils.o				\
 TlVector.o				

P_OBJS = \
 DfCalcGridX_Parallel.o			\
 DfCleanup_Parallel.o			\
 DfConvcheck_Parallel.o			\
 DfConverge_Anderson_Parallel.o		\
 DfConverge_Damping_Parallel.o		\
 DfDensityFitting_Parallel.o		\
 DfDensityFittingX_Parallel.o		\
 DfDensityFittingX_ScaLAPACK.o		\
 DfDiffDensityMatrix_Parallel.o		\
 DfDiagonal_Parallel.o			\
 DfDmatrix_Parallel.o			\
 DfEri_Parallel.o			\
 DfEri2_Parallel.o			\
 DfEriX_Parallel.o			\
 DfForce_Parallel.o			\
 DfFockMatrix_Parallel.o		\
 DfGenerateGrid_Parallel.o		\
 DfHpq_Parallel.o			\
 DfHpqX_Parallel.o			\
 DfInitialGuess_Parallel.o		\
 DfInputdata_Parallel.o			\
 DfIntegrals_Parallel.o			\
 DfInvMatrix_Parallel.o			\
 DfJMatrix_Parallel.o			\
 DfOverlap_Parallel.o			\
 DfOverlapX_Parallel.o			\
 DfPopulation_Parallel.o		\
 DfPreScf_Parallel.o			\
 DfScf_Parallel.o			\
 DfSummary_Parallel.o			\
 DfTaskCtrl_Parallel.o			\
 DfTotalEnergy_Parallel.o		\
 DfTransFmatrix_Parallel.o		\
 DfTwoElectronIntegral_Parallel.o	\
 DfTransatob_Parallel.o			\
 DfXCFunctional_Parallel.o		\
 DfXMatrix_Parallel.o			\
 ProteinDF_Parallel.o			\
 TlDistributeMatrix.o			\
 TlDistributeSymmetricMatrix.o		\
 TlDistributeVector.o			


CXX = mpiFCC
CXXFLAGS = \
 -DHAVE_LAPACK -DHAVE_SCALAPACK -DNDEBUG -DHAVE_CONFIG_H -O3 -Kfast -KOMP \
 -SCALAPACK -SSL2MPI -SSL2BLAMP
LIBS= -lstd

.SUFFIXES: .o .cpp .cxx

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $<

.cxx.o:
	$(CXX) $(CXXFLAGS) -c $<


.PHONY: all clean
all:	PDF.x PPDF.x

clean:
	$(RM) $(OBJS) $(P_OBJS) main.o  main_Parallel.o 

PDF.x:	main.o $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LAPACK_LIB) $(LIBS)

PPDF.x:	main_Parallel.o	$(OBJS) $(P_OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(SCALAPACK_LIB) $(LAPACK_LIB) $(LIBS)


