OBJS = \
 CnError.o			\
 DfCalcGrid.o			\
 DfCalcGridX.o			\
 DfCD.o				\
 DfCleanup.o			\
 DfConvcheck.o			\
 DfConverge.o			\
 DfConverge2.o			\
 DfConverge_Anderson.o		\
 DfConverge_Damping.o		\
 DfCqclomatrix.o		\
 DfDensityFittingX.o		\
 DfDiagonal.o			\
 DfDiffDensityMatrix.o		\
 DfDmatrix.o			\
 DfEri.o			\
 DfEri2.o			\
 DfEriEngine.o			\
 DfEriX.o			\
 DfFockMatrix.o			\
 DfForce.o			\
 DfFunctional.o			\
 DfFunctional_B3LYP.o		\
 DfFunctional_B88LYP.o		\
 DfFunctional_Becke88.o		\
 DfFunctional_Becke88_ExceptLDA.o	\
 DfFunctional_LYP.o			\
 DfFunctional_PW91X.o			\
 DfFunctional_SHF.o			\
 DfFunctional_SVWN.o			\
 DfFunctional_Slater.o			\
 DfFunctional_VWN.o			\
 DfFunctional_VWN3.o			\
 DfGenerateGrid.o			\
 DfHpq.o				\
 DfHpqEngine.o				\
 DfHpq_driver.o				\
 DfHpqX.o				\
 DfInitialGuess.o			\
 DfInitialGuessHarris.o			\
 DfInitialGuessHuckel.o			\
 DfInitialguess.o			\
 DfInputdata.o				\
 DfIntegrals.o				\
 DfInvMatrix.o				\
 DfJMatrix.o				\
 DfKMatrix.o				\
 DfLevelshift.o				\
 DfObject.o				\
 DfOverlap.o				\
 DfOverlapEngine.o			\
 DfOverlapX.o				\
 DfPopulation.o				\
 DfPreScf.o				\
 DfQclo.o				\
 DfScf.o				\
 DfSummary.o				\
 DfTaskCtrl.o				\
 DfTEI.o				\
 DfThreeindexintegrals.o		\
 DfTotalEnergy.o			\
 DfTransFmatrix.o			\
 DfTransatob.o				\
 DfTwoElectronIntegral.o		\
 DfXCFunctional.o			\
 DfXMatrix.o				\
 FileX.o				\
 Fl_Database.o				\
 Fl_Db_Basis.o				\
 Fl_Fragment.o				\
 Fl_Geometry.o				\
 Fl_GlobalinputX.o			\
 Fl_Gto.o				\
 Fl_GuessDB.o				\
 Fl_Tbl_AtomFragment.o			\
 Fl_Tbl_Density.o			\
 Fl_Tbl_Fragment.o			\
 Fl_Tbl_Orbital.o			\
 Fl_Tbl_Xcpot.o				\
 Fl_Tbl_Xcpot2.o			\
 Fl_Vct_Table.o				\
 PdfKeyword.o				\
 PdfUserInput.o				\
 PdfUtils.o				\
 ProteinDF.o				\
 TlAngularMomentumVector.o              \
 TlAngularMomentumVectorSet.o		\
 TlAtom.o				\
 TlColVectorMatrix2.o			\
 TlCombineDensityMatrix.o		\
 TlFile.o				\
 TlFileMatrix.o				\
 TlFileSymmetricMatrix.o		\
 TlFmt.o				\
 TlFname.o				\
 TlGetopt.o				\
 TlLogging.o				\
 TlMath.o				\
 TlMatrix.o				\
 TlMatrixCache.o			\
 TlMatrixObject.o			\
 TlMemManager.o				\
 TlMsgPack.o				\
 TlOrbitalInfo.o			\
 TlOrbitalInfoObject.o			\
 TlOrbitalInfo_Density.o		\
 TlOrbitalInfo_XC.o			\
 TlParameter.o				\
 TlPartialMatrix.o			\
 TlPartialSymmetricMatrix.o		\
 TlPosition.o				\
 TlPrdctbl.o				\
 TlPseudoYaml.o				\
 TlResidue.o				\
 TlRowVectorMatrix2.o			\
 TlSerializeData.o			\
 TlSparseMatrix.o			\
 TlSparseSymmetricMatrix.o		\
 TlSparseVectorMatrix.o			\
 TlStringTokenizer.o			\
 TlSymmetricMatrix.o			\
 TlSystem.o				\
 TlTime.o				\
 TlUtils.o				\
 TlVector.o				

P_OBJS = \
 DfCalcGridX_Parallel.o			\
 DfCleanup_Parallel.o			\
 DfConvcheck_Parallel.o			\
 DfConverge_Anderson_Parallel.o		\
 DfConverge_Damping_Parallel.o		\
 DfCD_Parallel.o			\
 DfDensityFittingX_Parallel.o		\
 DfDensityFittingX_ScaLAPACK.o		\
 DfDiffDensityMatrix_Parallel.o		\
 DfDiagonal_Parallel.o			\
 DfDmatrix_Parallel.o			\
 DfEri_Parallel.o			\
 DfEri2_Parallel.o			\
 DfEriX_Parallel.o			\
 DfForce_Parallel.o			\
 DfFockMatrix_Parallel.o		\
 DfGenerateGrid_Parallel.o		\
 DfHpq_Parallel.o			\
 DfHpqX_Parallel.o			\
 DfInitialGuess_Parallel.o		\
 DfInputdata_Parallel.o			\
 DfIntegrals_Parallel.o			\
 DfInvMatrix_Parallel.o			\
 DfJMatrix_Parallel.o			\
 DfKMatrix_Parallel.o			\
 DfOverlap_Parallel.o			\
 DfOverlapX_Parallel.o			\
 DfPopulation_Parallel.o		\
 DfPreScf_Parallel.o			\
 DfScf_Parallel.o			\
 DfSummary_Parallel.o			\
 DfTaskCtrl_Parallel.o			\
 DfTotalEnergy_Parallel.o		\
 DfTransFmatrix_Parallel.o		\
 DfTwoElectronIntegral_Parallel.o	\
 DfTransatob_Parallel.o			\
 DfXCFunctional_Parallel.o		\
 DfXMatrix_Parallel.o			\
 ProteinDF_Parallel.o			\
 TlCommunicate.o			\
 TlDistributeMatrix.o			\
 TlDistributeSymmetricMatrix.o		\
 TlDistributeVector.o			

CC = mpifccpx
CXX = mpiFCCpx

#CFLAGS = -DHAVE_CONFIG_H -Kfast -Kopenmp -Kocl -Kpreex -Karray_private -SSL2BLAMP -SCALAPACK

# success
#CFLAGS = -DHAVE_CONFIG_H -Kfast -Kocl -Kpreex -Karray_private -SSL2BLAMP -SCALAPACK
#CFLAGS = \
# -DHAVE_CONFIG_H -Kfast -Kocl -Kpreex -Karray_private \
# -Kparallel -Kregion_extension -Koptmsg=2 \
# -SSL2BLAMP -SCALAPACK

# 2012.04.26
#CFLAGS = \
# -DHAVE_CONFIG_H -Kfast,openmp \
# -SSL2BLAMP -SCALAPACK

CFLAGS = \
 -DHAVE_CONFIG_H \
 -O3 -Kfast -Kocl -Kpreex -Karray_private -Kregion_extension -Kparallel \
 -Kopenmp \
 -SSL2BLAMP -SCALAPACK

CXXFLAGS = $(CFLAGS)

.SUFFIXES: .o .cc .cpp .cxx

.cc.o:
	$(CC) $(CFLAGS) -c $<

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $<

.cxx.o:
	$(CXX) $(CXXFLAGS) -c $<


.PHONY: all clean install
all:	PDF.x PPDF.x pdfdivmat

clean:
	$(RM) *.o *.x

PDF.x:	main.o $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LAPACK_LIB) $(LIBS)

PPDF.x:	main_Parallel.o	$(OBJS) $(P_OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(SCALAPACK_LIB) $(LAPACK_LIB) $(LIBS)

pdfdivmat: main_pdfdivmat.cpp $(OBJS) $(P_OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(SCALAPACK_LIB) $(LAPACK_LIB) $(LIBS)

test_DensFit.x: main_testDensFit.o $(OBJS) 
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LAPACK_LIB) $(LIBS)

test_ERI.x: main_testERI.o $(OBJS) 
	$(CXX) $(CXXFLAGS) -o $@ $^ $(SCALAPACK_LIB) $(LAPACK_LIB) $(LIBS)

test_XC.x: main_testXC.o $(OBJS) 
	$(CXX) $(CXXFLAGS) -o $@ $^ $(SCALAPACK_LIB) $(LAPACK_LIB) $(LIBS)

install: all
	mkdir -p $(PDF_HOME)
	mkdir -p $(PDF_HOME)/bin
	cp -r ../data $(PDF_HOME)
	cp PDF.x PPDF.x test_DensFit.x test_ERI.x test_XC.x $(PDF_HOME)/bin



